sudo: false
language: node_js
node_js: 8
script:
  - cd sample-1
  - npm run build
  - cd ../
install:
  - cd sample-1
  - npm install
  - cd ../
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master